version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 

    image: voyager2020/qaso_web
    # if both not provided Service web has neither an image nor a build context specified. At least one must be provided.
    
    # command: '/bin/sh -c "echo "Web server running @ http://127.0.0.1:8000/""'
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/qaso
    
    ports:
      - "8000:8000"

  database:
    image: redis